# Photo Frame Configuration
photos_directory: "C:/Users/marti/Pictures"  # Path to directory containing photos
display_time: "30s"                           # Time to display each photo (s=seconds, m=minutes, h=hours, d=days)
transition_time: "15s"                         # Transition time between photos (s=seconds, m=minutes, h=hours)
random_order: true                           # Whether to randomize photo order
blur_zoom_background: true                   # Apply blurred zoom background for non-matching aspect ratios

# Metadata Overlay Settings
show_metadata: true                          # Show photo metadata overlay
metadata_opacity: 50                         # Opacity of metadata overlay (0-100)
metadata_font: "segoeui.ttf"                 # Font for metadata overlay
metadata_point_size: 12                      # Point size for metadata font

# Clock Overlay Settings
show_clock: true                             # Show clock overlay
clock_position: "top-right"                   # Clock position (top-left, top-center, top-right, bottom-center)
clock_opacity: 50                             # Opacity of clock overlay (0-100)
clock_font: "segoeui.ttf"                    # Font for clock overlay
clock_point_size: 12                         # Point size for clock font
clock_format: "HH:mm ddd D MMM"               # Clock format (Arrow format)